language: node_js
node_js:
  - "6"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script: 
  - cd src
  - npm install -g angular-cli
  - npm install -g karma
  - npm install
script:
  #- npm run pretest
  #- npm run test-coverage
  - npm run build
  
after_success:
  - ./node_modules/.bin/codecov

addons:
  firefox: "latest"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    # required by node-gyp to build some packages
    packages:
    - g++-4.8
